INSERT INTO `Brand` (`name`) VALUES
('Soundcore'),
('Vaydeer'),
('VIPSIM'),
('SIDIANBAN'),
('STABILO'),
('MUNBYN'),
('Sweetzer & Orange'),
('GEAK'),
('METRONIC'),
('Panasonic'),
('Roneky'),
('Belkin'),
('KICKDOT'),
('Berirexrion'),
('On The Grip'),
('AZKAQA'),
('myCartridge'),
('UNIQOOO'),
('SABANI'),
('Klein Tools'),
('Snughome'),
('AINOPE'),
('Alpine Corporation'),
('Comfify'),
('Bkayp'),
('Aioneus'),
('FITTDYHE'),
('Google'),
('Kosmic Soul'),
('LOVEVOOK'),
('ChicWrap'),
('MEKASS'),
('SFLHHDM'),
('COUNTRY FARMS'),
('CURMIO'),
('Silver Brush Limited'),
('Mr. Pen'),
('POPLOPP'),
('Saunders'),
('Quick Dam'),
('NEWEST'),
('HouseLabels'),
('Mount-It!'),
('T-Rex'),
('Americanflat'),
('Cleer'),
('Scotch'),
('UNIONE'),
('JBL'),
('DIGITNOW'),
('Knock Knock'),
('tomtoc'),
('Bright Standards'),
('Horizon Group USA'),
('DERMATOOL'),
('Reliaboard'),
('FEEL2NICE'),
('Viomis'),
('Shenzhen Xuanyang Technology Co., LTD'),
('Bush Furniture'),
('YoeeJob'),
('Fuumuui'),
('DYMO'),
('Urmust'),
('FORTEM'),
('SYNCWIRE'),
('Avantree'),
('Motsenbocker\'s Lift Off'),
('Cq acrylic'),
('NatureTouch'),
('Sharp'),
('SOLUX'),
('Officemate'),
('Youbetia'),
('FITUEYES'),
('LIUGX'),
('ESR'),
('FFtopu'),
('Note Tower'),
('Anker'),
('Seloom'),
('PrintWorks'),
('ReadyWise'),
('Neenah'),
('Fuxury'),
('AVERY'),
('Neosporin'),
('Adorox'),
('Ohuhu'),
('Binditek'),
('Canon'),
('PChero'),
('My Space Organizers'),
('HP'),
('BZBRLZ'),
('PNY'),
('Cricut'),
('Saiboro'),
('xydstay'),
('AOCHUAN'),
('Prismacolor'),
('MaxGear'),
('KOALA PAPER'),
('BONTEC'),
('Hovmwey'),
('Bostitch'),
('JUZARI'),
('HUANUO'),
('Paper Mate'),
('J. J. Keller & Associates, Inc.'),
('grwanpen'),
('ADHES TAPE PURSUIT OF PERFECTION'),
('MABOZOO'),
('AILIHEN'),
('Case it'),
('YOCTOSUN'),
('Gorilla Box'),
('Ugreen Group Limited'),
('Kaistyle'),
('Liquid I.V.'),
('Pawfly'),
('Vivifying'),
('FEMELI'),
('SMEAD'),
('Pentel'),
('Springhill'),
('Memoqueen'),
('iKammo'),
('Keebor'),
('MOSISO'),
('VANKEAN'),
('Fellowes'),
('Movo'),
('AM Case'),
('Paper Junkie'),
('Lifetime Supplies'),
('VIVO'),
('UniqueMe'),
('Marspark'),
('WOWBOX'),
('SHUTEX'),
('CloudValley'),
('SanDisk'),
('DRAPHY'),
('VELCRO Brand'),
('TANWIH'),
('TDLIRH'),
('CMTECK'),
('Soanufa'),
('Simetufy'),
('GBC'),
('Photect'),
('EYZUTAK'),
('PARTPHONER'),
('EcoNugenics'),
('MyGradDay'),
('ANVIZ'),
('BE STRONGEST HOMEWARE X B S 2015'),
('XJI'),
('Mead'),
('AMUU'),
('Christian Art Gifts'),
('Gudui'),
('Lamicall'),
('ZSEEWCAM'),
('Nayrmaer'),
('Lipvina'),
('COMPLIANCE AUDIT CENTER'),
('Cosco'),
('UCGOU'),
('WOT I'),
('JIALAI HOME'),
('ATUMTEK'),
('Pilot'),
('Furmax'),
('R-fun'),
('Goton'),
('Bankers Box'),
('Gorilla'),
('Disney'),
('H HIFIHEAR'),
('VEVOR'),
('MEIXIAOVISNB58'),
('Bestway'),
('Ospelelf'),
('Casio'),
('XO Simple is Beauty'),
('Meuvcol'),
('CRANBURY'),
('Bocasal'),
('Golkcurx'),
('CushZone'),
('Dritz'),
('BAZIC Products'),
('Yealink'),
('Sooez'),
('Hammermill'),
('KOVOSCH'),
('Vixic'),
('NEWYES'),
('Brother'),
('U Brands'),
('CNK'),
('Uni-Ball'),
('Purple Papers'),
('Accokids'),
('Prosumer\'s Choice'),
('NUJOLI'),
('VUSIGN'),
('BESARME'),
('ITEFDTUTNE'),
('SentrySafe'),
('onelinkmore'),
('Smart Weigh'),
('Oleitodh'),
('RE ROUGH ENOUGH'),
('JEFURE'),
('Miracase'),
('leQuiven'),
('Vicimwann'),
('Ergodyne'),
('Epson'),
('JOY worker'),
('UNIIDECO'),
('Graphique'),
('E FBOCK'),
('luckystyle'),
('NGTeco'),
('Fishent'),
('Losong'),
('JSAUX'),
('BIC'),
('STYLUSHOME'),
('Limitless Innovations'),
('Mikirini'),
('Lauren Harold'),
('C-Line'),
('Richboom'),
('BOHDK'),
('LeapYouth'),
('Eyoyo'),
('TAGRY'),
('C CRYSTAL LEMON'),
('WSICSE'),
('X-Acto'),
('GRANNY SAYS'),
('Splendoress'),
('HOLEWOR'),
('ETRONIK'),
('Four Candies'),
('FIPKE'),
('Towjug'),
('Zaviko'),
('FiiO'),
('Ducki'),
('Aottom'),
('JTIEO'),
('Yoption'),
('CLOROX'),
('Durable'),
('TOPWOOZU'),
('LEPOWER'),
('Weewooday'),
('AdTech'),
('Westcott'),
('NearHub'),
('Xtsuen'),
('QUEENLINK'),
('VIZ-PRO'),
('Lirches'),
('GOLD SEAL'),
('Coolpow'),
('EPABINA'),
('JOYBOS'),
('MAGIC JOHN'),
('Sherr'),
('Abudada'),
('AIOPTO'),
('maxtek'),
('MAGEASY'),
('qirita'),
('CoguZed'),
('plustek'),
('Bsrezn'),
('Duck'),
('KobraTech'),
('CallToU'),
('DEVAISE'),
('ACCUTECK'),
('Lreedy'),
('Pacon'),
('ScanSnap'),
('Dahle'),
('MOFT'),
('JonXon'),
('EOOUT'),
('Hoiny'),
('Mod Podge'),
('Aobabo'),
('AACL'),
('PokeLabel'),
('Stylo'),
('Morjor'),
('GreatYYT'),
('FOCUS DAY'),
('Benefiber'),
('INNOSUB'),
('ZYAOTWQZ'),
('KERIFI'),
('EDIMENS'),
('Legend Planner'),
('Rocketbook'),
('Mind Reader'),
('Storage Standard'),
('Westinghouse'),
('MYTONER'),
('Cable Matters'),
('Safco'),
('SHARPIE'),
('HAUTOCO'),
('BODFPPC'),
('Amasuki'),
('TUMABER'),
('WC'),
('XINLEI'),
('SupeDesk'),
('HOOBRO'),
('RIEJIN'),
('HAPPRUN'),
('Post-it'),
('L LIKED'),
('THINKWORK'),
('Lockways'),
('HUGGIES'),
('JOYFAR'),
('Colemoly'),
('YIVIGA'),
('Honey-Can-Do'),
('JADENS'),
('Wallaroo'),
('Jabra'),
('AMERTEER'),
('Aussumy'),
('ENGPOW'),
('TC-HOMENY'),
('Decorably'),
('Ortizan'),
('STKJoviale'),
('Learn & Climb'),
('HumanCentric'),
('Amazon Basics'),
('HA SHI'),
('Wristitani'),
('PAPRMA'),
('Ebanel'),
('Prazoli Products'),
('Amlits'),
('SpriteGru'),
('nextlifei'),
('SUDLTO'),
('Behringer'),
('Globe-Weis'),
('Anylabel'),
('Micro Ingredients'),
('MaxWorks'),
('ECR4Kids'),
('PAG'),
('WixGear'),
('weBoost'),
('AKAYOK'),
('Flash Furniture'),
('Drdefi'),
('Zotemo'),
('valkit'),
('OLLY'),
('Essex Wares'),
('CY craft'),
('TANTO'),
('MillHome'),
('Eagle'),
('Sinjimoru'),
('CYAFIXED'),
('Shanghai Norwii Technology Co., Ltd'),
('AT-A-GLANCE'),
('YOLAKIS'),
('MACTREM'),
('Nulaxy'),
('XANAD'),
('Kendir'),
('Lexar'),
('Cuttte'),
('SoloWIT'),
('IPO'),
('Aidunmis'),
('DocSafe'),
('Ljusmicker'),
('TWONE'),
('KIYODA'),
('DORFAS'),
('Pendaflex'),
('Naomi Home'),
('HYBSK'),
('LapGear'),
('CV CHARVORIA'),
('BlueSwan'),
('iClever'),
('Colorantic'),
('My Cinema Lightbox'),
('MODERN ART SUPPLIES A PRODUCT OF SMARTVISION CO'),
('KIHUWEY'),
('SS'),
('bloom daily planners'),
('SUXXAN'),
('vfaejll'),
('BZE'),
('Little ELF'),
('Swingline'),
('Kubohogar'),
('TORRAS'),
('SUNEE'),
('SVANTTO'),
('Slendor'),
('Neewer'),
('TEDNETGO'),
('MONVICT'),
('Dulums'),
('Loctite'),
('Liliyab'),
('Eicaus'),
('INIU'),
('OMOTON'),
('HDCRYSTALGIFTS'),
('Donner'),
('SUNITEC'),
('BLUE GINKGO'),
('Lee Products Co.'),
('diujzld'),
('BlueParrott'),
('CALDEVER'),
('QUOKKA'),
('Makeid'),
('Criacr'),
('MIATONE'),
('GMAOPHY'),
('Lospu HY'),
('TVON'),
('Dri Mark'),
('CABTE'),
('Nicpro'),
('The Can Converter'),
('Labelife'),
('FELICON'),
('NelkoGlobal'),
('KINGLAKE'),
('Crenova'),
('EXPO'),
('Ambertronix'),
('Oxford'),
('InnoGear'),
('Alliance'),
('Artstorys'),
('COIDEA'),
('VST'),
('Assark'),
('DYPER'),
('Tribe RN'),
('VALOME'),
('Ticonderoga'),
('Maledan'),
('Aureday'),
('Herda'),
('Zebra Pen'),
('HARTWII'),
('WANFRES'),
('ALKOO'),
('RAYSON'),
('Texas Instruments'),
('RIBAO TECHNOLOGY'),
('MLVOC'),
('WONGKUO'),
('Letaya'),
('bonsaii'),
('EIOTCLUB'),
('HUAPRINT'),
('Cndons'),
('We R Memory Keepers'),
('LC-dolida'),
('JUOIFIP'),
('SIBRILLE'),
('Wesiti'),
('MOKPR'),
('HOMOTEK'),
('Alumicolor'),
('Vlogging'),
('Outus'),
('CONTROLTEK'),
('Spigen'),
('Nadex'),
('Honeywell'),
('The Happy Planner'),
('F-color'),
('JIXZEN'),
('CukoHno'),
('Sinboun'),
('TOCOL'),
('Bubblefast'),
('M MAGDEPO'),
('Tomorotec'),
('Alolo'),
('Drawwind'),
('SAPITAL'),
('Sailstar'),
('JANYUN'),
('WoneNice'),
('ROYALITA'),
('YOREPEK'),
('BXUXOHS'),
('deli'),
('SUPERONE'),
('MATEIN'),
('Nite Ize'),
('Sutter Signs'),
('InterDesign'),
('Mity rain'),
('SEANTUA'),
('Nexkayee'),
('PopSockets'),
('DTUQYX'),
('Sdstone'),
('Joby'),
('Wristco'),
('Hoikwo'),
('Wantek'),
('Hugg-A-Planet'),
('Youhauchair'),
('Ytonet'),
('Motorola Sound'),
('American Greetings'),
('Kciplab'),
('hohem'),
('M&G'),
('Xinhelan'),
('NextDayLabels'),
('KOSMCCO'),
('MOZOTER'),
('Aisibeiger'),
('Scribbledo'),
('Voncerus'),
('SCHLAGE'),
('Simple Designs'),
('Quapkatt'),
('Vipcase'),
('Trustnice'),
('TOZO'),
('iMailer'),
('Sony'),
('LISEN'),
('NOW Foods'),
('WOD Tape'),
('WESTREE'),
('Tribit'),
('OCTOBUDDY'),
('Adir Corp.'),
('UEQ'),
('Boiron'),
('Tera'),
('windrio'),
('DARUNAXY'),
('iiteeology'),
('TAVR Furniture'),
('RED EMBER'),
('Umbra'),
('fansitc'),
('JILoffice'),
('Rite in the Rain'),
('Unitek'),
('Really Good Stuff'),
('iSYFIX'),
('KAER'),
('VEWINGL'),
('MASAKA B&W'),
('ROARING SPRING'),
('CHEIGHY'),
('Svartur'),
('Take OFF Luggage'),
('GYIIYUO'),
('Memoking'),
('Blue Lake'),
('KOKUYO'),
('Smarpau'),
('ARTIFY art supplies'),
('Tiakia'),
('IRIS'),
('Aviditi'),
('WHAUU'),
('Zhengmy'),
('WiMiUS'),
('Royal Sovereign'),
('MSDADA'),
('ELDVAP'),
('Burasari'),
('MoKo'),
('Red Co.'),
('FaCraft'),
('VOPLLS'),
('Tribesigns'),
('Winsor & Newton'),
('ALVIN'),
('Tassel Depot'),
('elago'),
('Waterpik'),
('KYODOLED'),
('Escoda'),
('XINBAOHONG'),
('Gixxted'),
('Speedball'),
('Coboll'),
('YPLUS'),
('VASAGLE'),
('Kensington'),
('Bonbela'),
('Gecko Travel Tech'),
('Boean'),
('Tarifold'),
('BEFSOP'),
('NADAMOO'),
('KEYPOWER'),
('KOOLDE'),
('YSSOA'),
('Jovanssen'),
('LOVFIVE'),
('Paper Plan'),
('XITDW'),
('QILIMA'),
('Ninitch'),
('SmartSign'),
('smart planner'),
('BYNSOE'),
('Lemas'),
('Bsz4uov'),
('STUDIOSTONE CREATIVE'),
('WeiYue'),
('LAMEEKU'),
('Dilzekui'),
('Roylco'),
('ClearBags'),
('cudinham'),
('Chunful'),
('Brightech'),
('Faber-Castell'),
('kurdene'),
('Hoqqf'),
('podoru'),
('UBeesize'),
('NITMTYOU'),
('Shintop'),
('SKYDUE'),
('SAM & LORI'),
('THINK2MASTER'),
('SHOKZ'),
('YLOLUL'),
('Dunwell'),
('Floortex'),
('Knild'),
('Sukh'),
('Famassi'),
('Mahensy'),
('Spiareal'),
('VICSEED'),
('Yangmei'),
('Healthy Origins'),
('&And Per Se'),
('LaBold'),
('Yistao'),
('JvKzaen'),
('SKIUDCT'),
('Tile'),
('AIWOQI'),
('Bose'),
('Tossbiss'),
('Hion'),
('DECOHS'),
('Moleskine'),
('LOUTYTUO'),
('zzhxkjhky'),
('JYLH JOYSEEKER'),
('Charmast'),
('YOPCDJ'),
('L LTGEM'),
('BOLISS'),
('RUNBACH'),
('xiwxi'),
('EcoNour'),
('Samsill'),
('Ailun'),
('COZEFFIC'),
('SSLOTSCASE'),
('LingLingo'),
('BETCKEY'),
('Surebonder'),
('BONSEN'),
('thinkor'),
('MarkDomain'),
('xydled'),
('SAKEYR'),
('Skullcandy'),
('Volcora'),
('KOSCHEAL'),
('Super Glue'),
('Tsytyst'),
('ZEQUAN'),
('Five Star'),
('Godefa'),
('CHUNNIAO'),
('Clever Fox'),
('UPINS'),
('TOMKID'),
('BOSMILLER'),
('EVETTO'),
('Wideskall'),
('cooloo8'),
('AISNI'),
('1 Hora'),
('Luckyear'),
('NAMON'),
('Metamucil'),
('Reyke'),
('Symcele'),
('POCHAR'),
('Boao'),
('BesWin'),
('Anyongora'),
('DINOSTRIKE'),
('EooCoo'),
('Preparation H'),
('Targus'),
('Vitafusion'),
('AHGXG'),
('Juvale'),
('GEM AWARDS YOUR FULL SERVICE AWARDS STORE'),
('ZAGG'),
('HOMiDEK'),
('Asvine'),
('SHANSHUI'),
('PaperPro');
COMMIT;