INSERT INTO `u24569039_products` (`category`) VALUES
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Patio, Lawn & Garden'),
('Office Products'),
('Electronics'),
('Electronics'),
('Arts, Crafts & Sewing'),
('Cell Phones & Accessories'),
('Office Products'),
('Electronics'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Health & Household'),
('Electronics'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Tools & Home Improvement'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Home & Kitchen'),
('Electronics'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Health & Household'),
('Office Products'),
('Cell Phones & Accessories'),
('Arts, Crafts & Sewing'),
('Cell Phones & Accessories'),
('Home & Kitchen'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Electronics'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Home & Kitchen'),
('Tools & Home Improvement'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Health & Household'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Tools & Home Improvement'),
('Electronics'),
('Arts, Crafts & Sewing'),
('Cell Phones & Accessories'),
('Electronics'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Health & Household'),
('Office Products'),
('Electronics'),
('Cell Phones & Accessories'),
('Health & Household'),
('Office Products'),
('Tools & Home Improvement'),
('Office Products'),
('Office Products'),
('Office Products'),
('Patio, Lawn & Garden'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Electronics'),
('Office Products'),
('Electronics'),
('Electronics'),
('Office Products'),
('Cell Phones & Accessories'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Electronics'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Clothing, Shoes & Jewelry'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Tools & Home Improvement'),
('Health & Household'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Industrial & Scientific'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Cell Phones & Accessories'),
('Office Products'),
('Industrial & Scientific'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Patio, Lawn & Garden'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Industrial & Scientific'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Tools & Home Improvement'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Industrial & Scientific'),
('Cell Phones & Accessories'),
('Patio, Lawn & Garden'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Tools & Home Improvement'),
('Electronics'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Tools & Home Improvement'),
('Office Products'),
('Office Products'),
('Electronics'),
('Electronics'),
('Cell Phones & Accessories'),
('Office Products'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Home & Kitchen'),
('Office Products'),
('Hunting & Fishing'),
('Office Products'),
('Electronics'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Arts, Crafts & Sewing'),
('Arts, Crafts & Sewing'),
('Health & Household'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Tools & Home Improvement'),
('Arts, Crafts & Sewing'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Cell Phones & Accessories'),
('Patio, Lawn & Garden'),
('Tools & Home Improvement'),
('Home & Kitchen'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Electronics'),
('Cell Phones & Accessories'),
('Office Products'),
('Industrial & Scientific'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Health & Household'),
('Office Products'),
('Office Products'),
('Office Products'),
('Patio, Lawn & Garden'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Electronics'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Baby Products'),
('Cell Phones & Accessories'),
('Electronics'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Electronics'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Health & Household'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Patio, Lawn & Garden'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Health & Household'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Tools & Home Improvement'),
('Office Products'),
('Electronics'),
('Health & Household'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Arts, Crafts & Sewing'),
('Industrial & Scientific'),
('Office Products'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Electronics'),
('Office Products'),
('Cell Phones & Accessories'),
('Electronics'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Electronics'),
('Arts, Crafts & Sewing'),
('Tools & Home Improvement'),
('Arts, Crafts & Sewing'),
('Cell Phones & Accessories'),
('Tools & Home Improvement'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Electronics'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Cell Phones & Accessories'),
('Industrial & Scientific'),
('Electronics'),
('Office Products'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Electronics'),
('Office Products'),
('Electronics'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Tools & Home Improvement'),
('Office Products'),
('Office Products'),
('Office Products'),
('Tools & Home Improvement'),
('Office Products'),
('Electronics'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Baby Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Home & Kitchen'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Arts, Crafts & Sewing'),
('Cell Phones & Accessories'),
('Health & Household'),
('Office Products'),
('Tools & Home Improvement'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Patio, Lawn & Garden'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Electronics'),
('Office Products'),
('Tools & Home Improvement'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Office Products'),
('Electronics'),
('Cell Phones & Accessories'),
('Office Products'),
('Health & Household'),
('Patio, Lawn & Garden'),
('Sports & Outdoors'),
('Health & Household'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Hunting & Fishing'),
('Tools & Home Improvement'),
('Patio, Lawn & Garden'),
('Patio, Lawn & Garden'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Cell Phones & Accessories'),
('Electronics'),
('Cell Phones & Accessories'),
('Office Products'),
('Home & Kitchen'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Industrial & Scientific'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Tools & Home Improvement'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Toys & Games'),
('Office Products'),
('Electronics'),
('Patio, Lawn & Garden'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Tools & Home Improvement'),
('Office Products'),
('Tools & Home Improvement'),
('Cell Phones & Accessories'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Electronics'),
('Office Products'),
('Patio, Lawn & Garden'),
('Cell Phones & Accessories'),
('Health & Household'),
('Industrial & Scientific'),
('Office Products'),
('Electronics'),
('Electronics'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Health & Household'),
('Office Products'),
('Office Products'),
('Home & Kitchen'),
('Cell Phones & Accessories'),
('Electronics'),
('Office Products'),
('Office Products'),
('Electronics'),
('Home & Kitchen'),
('Office Products'),
('Office Products'),
('Patio, Lawn & Garden'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Hunting & Fishing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Clothing, Shoes & Jewelry'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Automotive'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Cell Phones & Accessories'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Health & Household'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Cell Phones & Accessories'),
('Electronics'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Patio, Lawn & Garden'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Electronics'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Industrial & Scientific'),
('Tools & Home Improvement'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Health & Household'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Tools & Home Improvement'),
('Office Products'),
('Cell Phones & Accessories'),
('Electronics'),
('Office Products'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Office Products'),
('Home & Kitchen'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Tools & Home Improvement'),
('Home & Kitchen'),
('Electronics'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Arts, Crafts & Sewing'),
('Health & Household'),
('Cell Phones & Accessories'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Electronics'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Sports & Outdoors'),
('Tools & Home Improvement'),
('Office Products'),
('Electronics'),
('Office Products'),
('Electronics'),
('Electronics'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Health & Household'),
('Cell Phones & Accessories'),
('Electronics'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Video Games'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Industrial & Scientific'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Electronics'),
('Patio, Lawn & Garden'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Arts, Crafts & Sewing'),
('Industrial & Scientific'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Cell Phones & Accessories'),
('Arts, Crafts & Sewing'),
('Electronics'),
('Health & Household'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Cell Phones & Accessories'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Electronics'),
('Office Products'),
('Arts, Crafts & Sewing'),
('Electronics'),
('Office Products'),
('Office Products'),
('Health & Household'),
('Electronics'),
('Office Products'),
('Cell Phones & Accessories'),
('Tools & Home Improvement'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Patio, Lawn & Garden'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Arts, Crafts & Sewing'),
('Office Products'),
('Electronics'),
('Health & Household'),
('Office Products'),
('Electronics'),
('Health & Household'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products'),
('Office Products'),
('Cell Phones & Accessories'),
('Office Products');
COMMIT;