INSERT INTO `Brand` (`name`) VALUES
('Soundcore'),
('Vaydeer'),
('VIPSIM'),
('SIDIANBAN'),
('STABILO'),
('MUNBYN'),
('Sweetzer & Orange'),
('GEAK'),
('METRONIC'),
('Panasonic'),
('Roneky'),
('Belkin'),
('KICKDOT'),
('Berirexrion'),
('On The Grip'),
('AZKAQA'),
('myCartridge'),
('UNIQOOO'),
('SABANI'),
('Klein Tools'),
('Snughome'),
('AINOPE'),
('Alpine Corporation'),
('Comfify'),
('Bkayp'),
('Aioneus'),
('FITTDYHE'),
('Google'),
('Kosmic Soul'),
('LOVEVOOK'),
('AINOPE'),
('ChicWrap'),
('MEKASS'),
('SFLHHDM'),
('COUNTRY FARMS'),
('CURMIO'),
('Silver Brush Limited'),
('Mr. Pen'),
('POPLOPP'),
('Saunders'),
('Quick Dam'),
('NEWEST'),
('HouseLabels'),
('Mount-It!'),
('T-Rex'),
('Americanflat'),
('Cleer'),
('Scotch'),
('UNIONE'),
('JBL'),
('DIGITNOW'),
('Knock Knock'),
('tomtoc'),
('Bright Standards'),
('Horizon Group USA'),
('DERMATOOL'),
('Reliaboard'),
('FEEL2NICE'),
('Viomis'),
('Shenzhen Xuanyang Technology Co., LTD'),
('Bush Furniture'),
('YoeeJob'),
('Fuumuui'),
('DYMO'),
('Urmust'),
('FORTEM'),
('SYNCWIRE'),
('Scotch'),
('Avantree'),
('Scotch'),
('Motsenbocker\'s Lift Off'),
('Cq acrylic'),
('NatureTouch'),
('Mr. Pen'),
('Sharp'),
('SOLUX'),
('Officemate'),
('Youbetia'),
('FITUEYES'),
('LIUGX'),
('ESR'),
('FFtopu'),
('Note Tower'),
('Anker'),
('Seloom'),
('PrintWorks'),
('Alpine Corporation'),
('ReadyWise'),
('Silver Brush Limited'),
('Neenah'),
('Fuxury'),
('AVERY'),
('Neosporin'),
('Adorox'),
('Ohuhu'),
('Binditek'),
('Canon'),
('PChero'),
('Scotch'),
('My Space Organizers'),
('HP'),
('BZBRLZ'),
('PNY'),
('Cricut'),
('Saiboro'),
('tomtoc'),
('xydstay'),
('AOCHUAN'),
('Prismacolor'),
('Silver Brush Limited'),
('MaxGear'),
('KOALA PAPER'),
('BONTEC'),
('UNIQOOO'),
('Hovmwey'),
('Bostitch'),
('JUZARI'),
('HUANUO'),
('Paper Mate'),
('J. J. Keller & Associates, Inc.'),
('grwanpen'),
('LOVEVOOK'),
('ADHES TAPE PURSUIT OF PERFECTION'),
('MABOZOO'),
('AILIHEN'),
('Case it'),
('YOCTOSUN'),
('Gorilla Box'),
('Ugreen Group Limited'),
('Kaistyle'),
('Liquid I.V.'),
('Pawfly'),
('Vivifying'),
('FEMELI'),
('SMEAD'),
('Pentel'),
('Alpine Corporation'),
('Springhill'),
('Memoqueen'),
('iKammo'),
('Keebor'),
('MOSISO'),
('VANKEAN'),
('Fellowes'),
('Movo'),
('AM Case'),
('Paper Junkie'),
('Lifetime Supplies'),
('VIVO'),
('UniqueMe'),
('SMEAD'),
('Marspark'),
('WOWBOX'),
('SHUTEX'),
('JBL'),
('CloudValley'),
('SanDisk'),
('DRAPHY'),
('VIVO'),
('VELCRO Brand'),
('TANWIH'),
('Officemate'),
('TDLIRH'),
('CMTECK'),
('Soanufa'),
('Simetufy'),
('GBC'),
('Photect'),
('EYZUTAK'),
('PARTPHONER'),
('EcoNugenics'),
('Belkin'),
('MyGradDay'),
('ANVIZ'),
('BE STRONGEST HOMEWARE X B S 2015'),
('XJI'),
('Mead'),
('AMUU'),
('Christian Art Gifts'),
('Gudui'),
('ESR'),
('Lamicall'),
('ZSEEWCAM'),
('Nayrmaer'),
('Lipvina'),
('COMPLIANCE AUDIT CENTER'),
('Cosco'),
('UCGOU'),
('WOT I'),
('JIALAI HOME'),
('ATUMTEK'),
('Pilot'),
('HP'),
('Furmax'),
('R-fun'),
('Goton'),
('Bankers Box'),
('Gorilla'),
('HUANUO'),
('HP'),
('AVERY'),
('Disney'),
('H HIFIHEAR'),
('VEVOR'),
('MEIXIAOVISNB58'),
('Bestway'),
('Ospelelf'),
('Casio'),
('XO Simple is Beauty'),
('Meuvcol'),
('Fellowes'),
('AVERY'),
('Fellowes'),
('CRANBURY'),
('Bocasal'),
('Golkcurx'),
('CushZone'),
('Dritz'),
('BAZIC Products'),
('Yealink'),
('Sooez'),
('Hammermill'),
('KOVOSCH'),
('Vixic'),
('NEWYES'),
('Brother'),
('Soundcore'),
('U Brands'),
('CNK'),
('KOALA PAPER'),
('Uni-Ball'),
('Purple Papers'),
('Accokids'),
('Alpine Corporation'),
('Prosumer\'s Choice'),
('NUJOLI'),
('VUSIGN'),
('KOALA PAPER'),
('BESARME'),
('ITEFDTUTNE'),
('SentrySafe'),
('onelinkmore'),
('Smart Weigh'),
('Oleitodh'),
('RE ROUGH ENOUGH'),
('JEFURE'),
('SMEAD'),
('Miracase'),
('leQuiven'),
('Vicimwann'),
('Ergodyne'),
('Epson'),
('AVERY'),
('JOY worker'),
('UNIIDECO'),
('Graphique'),
('E FBOCK'),
('luckystyle'),
('NGTeco'),
('Fishent'),
('Losong'),
('JSAUX'),
('UGREEN GROUP LIMITED'),
('BIC'),
('STYLUSHOME'),
('SYNCWIRE'),
('Limitless Innovations'),
('Mikirini'),
('Mount-It!'),
('Lauren Harold'),
('C-Line'),
('Richboom'),
('BOHDK'),
('LeapYouth'),
('Eyoyo'),
('TAGRY'),
('C CRYSTAL LEMON'),
('WSICSE'),
('MaxGear'),
('X-Acto'),
('GRANNY SAYS'),
('Splendoress'),
('HOLEWOR'),
('AVERY'),
('SanDisk'),
('MUNBYN'),
('ETRONIK'),
('Four Candies'),
('FIPKE'),
('Towjug'),
('Zaviko'),
('FiiO'),
('Ducki'),
('Aottom'),
('JTIEO'),
('Yoption'),
('CLOROX'),
('Durable'),
('Hammermill'),
('TOPWOOZU'),
('LEPOWER'),
('Weewooday'),
('AdTech'),
('Westcott'),
('NearHub'),
('Xtsuen'),
('QUEENLINK'),
('VIZ-PRO'),
('AVERY'),
('Lirches'),
('GOLD SEAL'),
('Coolpow'),
('Alpine Corporation'),
('EPABINA'),
('JOYBOS'),
('MAGIC JOHN'),
('Sherr'),
('Abudada'),
('AIOPTO'),
('Lipvina'),
('maxtek'),
('Brother'),
('MAGEASY'),
('qirita'),
('SMEAD'),
('CoguZed'),
('plustek'),
('Bsrezn'),
('Duck'),
('KobraTech'),
('CallToU'),
('DEVAISE'),
('ACCUTECK'),
('Lreedy'),
('Pacon'),
('ScanSnap'),
('Dahle'),
('MOFT'),
('JonXon'),
('EOOUT'),
('Hoiny'),
('Mod Podge'),
('Aobabo'),
('Canon'),
('Fuumuui'),
('AACL'),
('PokeLabel'),
('VIVO'),
('Stylo'),
('Morjor'),
('GreatYYT'),
('FOCUS DAY'),
('Benefiber'),
('INNOSUB'),
('ZYAOTWQZ'),
('KERIFI'),
('Alpine Corporation'),
('EDIMENS'),
('Legend Planner'),
('Rocketbook'),
('Mind Reader'),
('Storage Standard'),
('Westinghouse'),
('MYTONER'),
('Cable Matters'),
('Canon'),
('AVERY'),
('Safco'),
('SHARPIE'),
('HAUTOCO'),
('BODFPPC'),
('Amasuki'),
('TUMABER'),
('WC'),
('Fellowes'),
('AVERY'),
('SHARPIE'),
('XINLEI'),
('SupeDesk'),
('HOOBRO'),
('RIEJIN'),
('myCartridge'),
('HAPPRUN'),
('Post-it'),
('L LIKED'),
('SMEAD'),
('THINKWORK'),
('AVERY'),
('Lockways'),
('HUGGIES'),
('JOYFAR'),
('JBL'),
('Colemoly'),
('SMEAD'),
('YIVIGA'),
('Honey-Can-Do'),
('JADENS'),
('BAZIC Products'),
('Wallaroo'),
('Jabra'),
('AMERTEER'),
('Aussumy'),
('ENGPOW'),
('TC-HOMENY'),
('Scotch'),
('Decorably'),
('Mead'),
('Ortizan'),
('STKJoviale'),
('Fuxury'),
('Learn & Climb'),
('SMEAD'),
('HumanCentric'),
('Amazon Basics'),
('Prismacolor'),
('HA SHI'),
('Wristitani'),
('PAPRMA'),
('Sharp'),
('Ebanel'),
('Prazoli Products'),
('Westcott'),
('Amlits'),
('SpriteGru'),
('nextlifei'),
('SHARPIE'),
('SUDLTO'),
('Alpine Corporation'),
('Behringer'),
('Globe-Weis'),
('SMEAD'),
('Anylabel'),
('Micro Ingredients'),
('MaxWorks'),
('ECR4Kids'),
('PAG'),
('WixGear'),
('weBoost'),
('AKAYOK'),
('Amazon Basics'),
('Flash Furniture'),
('Drdefi'),
('Zotemo'),
('valkit'),
('OLLY'),
('BIC'),
('BIC'),
('Amazon Basics'),
('Essex Wares'),
('CY craft'),
('TANTO'),
('Scotch'),
('MillHome'),
('Eagle'),
('Sinjimoru'),
('Adtech'),
('CYAFIXED'),
('Shanghai Norwii Technology Co., Ltd'),
('AT-A-GLANCE'),
('YOLAKIS'),
('MACTREM'),
('Nulaxy'),
('XANAD'),
('Westcott'),
('tomtoc'),
('Flash Furniture'),
('Kendir'),
('Lexar'),
('Cuttte'),
('SoloWIT'),
('IPO'),
('Aidunmis'),
('Pentel'),
('DocSafe'),
('Ljusmicker'),
('TWONE'),
('KIYODA'),
('DORFAS'),
('Sooez'),
('Pendaflex'),
('Naomi Home'),
('HYBSK'),
('LapGear'),
('SMEAD'),
('CV CHARVORIA'),
('BlueSwan'),
('iClever'),
('Colorantic'),
('My Cinema Lightbox'),
('MODERN ART SUPPLIES A PRODUCT OF SMARTVISION CO'),
('KIHUWEY'),
('Amazon Basics'),
('SS'),
('bloom daily planners'),
('SUXXAN'),
('vfaejll'),
('BZE'),
('Little ELF'),
('HP'),
('Pendaflex'),
('Swingline'),
('Kubohogar'),
('TORRAS'),
('SUNEE'),
('SVANTTO'),
('Slendor'),
('Neewer'),
('HYBSK'),
('PNY'),
('TEDNETGO'),
('MONVICT'),
('Dulums'),
('Loctite'),
('SanDisk'),
('Liliyab'),
('Eicaus'),
('INIU'),
('OMOTON'),
('HDCRYSTALGIFTS'),
('Donner'),
('SUNITEC'),
('BLUE GINKGO'),
('Pilot'),
('Mr. Pen'),
('Lee Products Co.'),
('HP'),
('diujzld'),
('BlueParrott'),
('CALDEVER'),
('QUOKKA'),
('Paper Mate'),
('Makeid'),
('HP'),
('Criacr'),
('MIATONE'),
('JADENS'),
('WOT I'),
('Pendaflex'),
('Scotch'),
('GMAOPHY'),
('Lospu HY'),
('Coolpow'),
('TVON'),
('Dri Mark'),
('CABTE'),
('Nicpro'),
('The Can Converter'),
('Labelife'),
('FELICON'),
('NelkoGlobal'),
('KINGLAKE'),
('Crenova'),
('Anker'),
('EXPO'),
('Ambertronix'),
('Oxford'),
('InnoGear'),
('Alliance'),
('Artstorys'),
('COIDEA'),
('VST'),
('Assark'),
('AVERY'),
('DYPER'),
('Tribe RN'),
('VALOME'),
('Ticonderoga'),
('Goton'),
('Maledan'),
('Brother'),
('Aureday'),
('HP'),
('Herda'),
('Zebra Pen'),
('BIC'),
('C-Line'),
('HARTWII'),
('WANFRES'),
('VIZ-PRO'),
('ALKOO'),
('RAYSON'),
('Amazon Basics'),
('SUNEE'),
('Texas Instruments'),
('RIBAO TECHNOLOGY'),
('MLVOC'),
('WONGKUO'),
('Letaya'),
('BIC'),
('bonsaii'),
('EIOTCLUB'),
('DYMO'),
('HUAPRINT'),
('Cndons'),
('We R Memory Keepers'),
('LC-dolida'),
('JUOIFIP'),
('Scotch'),
('SIBRILLE'),
('Wesiti'),
('MOKPR'),
('AVERY'),
('Alpine Corporation'),
('SUNEE'),
('HOMOTEK'),
('PAG'),
('Alumicolor'),
('Vlogging'),
('Ticonderoga'),
('Outus'),
('CONTROLTEK'),
('Spigen'),
('Nadex'),
('MOSISO'),
('BESARME'),
('Honeywell'),
('Bostitch'),
('The Happy Planner'),
('F-color'),
('Post-it'),
('JIXZEN'),
('Mr. Pen'),
('JSAUX'),
('CukoHno'),
('Sinboun'),
('JBL'),
('TOCOL'),
('Bubblefast'),
('M MAGDEPO'),
('Alpine Corporation'),
('ReadyWise'),
('Benefiber'),
('Tomorotec'),
('Alolo'),
('Drawwind'),
('Outus'),
('SAPITAL'),
('Sailstar'),
('Alpine Corporation'),
('Alpine Corporation'),
('JANYUN'),
('LIUGX'),
('WoneNice'),
('Safco'),
('ROYALITA'),
('SMEAD'),
('YOREPEK'),
('Brother'),
('BXUXOHS'),
('deli'),
('SUPERONE'),
('MATEIN'),
('Nite Ize'),
('Sutter Signs'),
('InterDesign'),
('Mity rain'),
('SEANTUA'),
('Nexkayee'),
('PopSockets'),
('Oxford'),
('DTUQYX'),
('Sdstone'),
('Joby'),
('FITUEYES'),
('Wristco'),
('Hoikwo'),
('Wantek'),
('Hugg-A-Planet'),
('Youhauchair'),
('Ytonet'),
('Alpine Corporation'),
('Silver Brush Limited'),
('Duck'),
('Motorola Sound'),
('American Greetings'),
('Kciplab'),
('hohem'),
('M&G'),
('Xinhelan'),
('NextDayLabels'),
('KOSMCCO'),
('MOZOTER'),
('UNIQOOO'),
('Paper Mate'),
('Canon'),
('Aisibeiger'),
('Scribbledo'),
('Voncerus'),
('SCHLAGE'),
('Simple Designs'),
('ESR'),
('Quapkatt'),
('Vipcase'),
('Trustnice'),
('VIVO'),
('TOZO'),
('iMailer'),
('Sony'),
('AVERY'),
('Alpine Corporation'),
('LISEN'),
('NOW Foods'),
('WOD Tape'),
('AVERY'),
('WESTREE'),
('Tribit'),
('OCTOBUDDY'),
('Mr. Pen'),
('Adir Corp.'),
('BlueParrott'),
('UEQ'),
('Boiron'),
('Tera'),
('windrio'),
('DARUNAXY'),
('iiteeology'),
('TAVR Furniture'),
('AVERY'),
('RED EMBER'),
('Anker'),
('Umbra'),
('fansitc'),
('JILoffice'),
('Alpine Corporation'),
('Officemate'),
('Rite in the Rain'),
('Unitek'),
('Sweetzer & Orange'),
('Really Good Stuff'),
('iSYFIX'),
('KAER'),
('HAUTOCO'),
('Scotch'),
('VEWINGL'),
('MASAKA B&W'),
('ROARING SPRING'),
('CHEIGHY'),
('Svartur'),
('Take OFF Luggage'),
('GYIIYUO'),
('ScanSnap'),
('Memoking'),
('Blue Lake'),
('KOKUYO'),
('EXPO'),
('SanDisk'),
('Smarpau'),
('Note Tower'),
('EXPO'),
('ARTIFY art supplies'),
('Tiakia'),
('IRIS'),
('Aviditi'),
('WHAUU'),
('Scotch'),
('Zhengmy'),
('WiMiUS'),
('Royal Sovereign'),
('MSDADA'),
('CONTROLTEK'),
('Pilot'),
('ELDVAP'),
('Burasari'),
('MoKo'),
('TOPWOOZU'),
('Red Co.'),
('FaCraft'),
('VOPLLS'),
('Tribesigns'),
('Google'),
('Winsor & Newton'),
('AVERY'),
('ALVIN'),
('Tassel Depot'),
('elago'),
('Waterpik'),
('KYODOLED'),
('Escoda'),
('XINBAOHONG'),
('Gixxted'),
('Speedball'),
('Coboll'),
('YPLUS'),
('XINBAOHONG'),
('AVERY'),
('VASAGLE'),
('Alpine Corporation'),
('Kensington'),
('Bonbela'),
('Gecko Travel Tech'),
('Flash Furniture'),
('Boean'),
('Tarifold'),
('Lexar'),
('BEFSOP'),
('NADAMOO'),
('Zaviko'),
('KEYPOWER'),
('KOOLDE'),
('YSSOA'),
('Jovanssen'),
('LOVFIVE'),
('Paper Plan'),
('XITDW'),
('QILIMA'),
('Ninitch'),
('SmartSign'),
('smart planner'),
('BYNSOE'),
('CNK'),
('Lemas'),
('Bsz4uov'),
('STUDIOSTONE CREATIVE'),
('WeiYue'),
('Nicpro'),
('LAMEEKU'),
('Dilzekui'),
('Roylco'),
('ClearBags'),
('Epson'),
('cudinham'),
('Chunful'),
('Scotch'),
('Brightech'),
('Faber-Castell'),
('Lamicall'),
('kurdene'),
('Hoqqf'),
('podoru'),
('Coolpow'),
('Paper Junkie'),
('Flash Furniture'),
('UBeesize'),
('NITMTYOU'),
('Shintop'),
('Alpine Corporation'),
('SanDisk'),
('SKYDUE'),
('Soundcore'),
('Epson'),
('Hammermill'),
('SAM & LORI'),
('BIC'),
('THINK2MASTER'),
('SHOKZ'),
('YLOLUL'),
('Dunwell'),
('Paper Mate'),
('Floortex'),
('KOKUYO'),
('BAZIC Products'),
('Knild'),
('Sukh'),
('Rite in the Rain'),
('deli'),
('Famassi'),
('Mahensy'),
('Fellowes'),
('Spiareal'),
('VICSEED'),
('Yangmei'),
('Healthy Origins'),
('Lipvina'),
('&And Per Se'),
('LaBold'),
('Oxford'),
('Yistao'),
('JvKzaen'),
('SKIUDCT'),
('ReadyWise'),
('Simple Designs'),
('Mr. Pen'),
('Tile'),
('AIWOQI'),
('Bose'),
('Tossbiss'),
('SUNEE'),
('Ticonderoga'),
('Pilot'),
('Hion'),
('DECOHS'),
('Moleskine'),
('LOUTYTUO'),
('KYODOLED'),
('On The Grip'),
('zzhxkjhky'),
('bloom daily planners'),
('Officemate'),
('JYLH JOYSEEKER'),
('YOCTOSUN'),
('Charmast'),
('MOSISO'),
('Silver Brush Limited'),
('YOPCDJ'),
('Pendaflex'),
('L LTGEM'),
('Mead'),
('BOLISS'),
('RUNBACH'),
('xiwxi'),
('EcoNour'),
('AVERY'),
('Samsill'),
('Ailun'),
('Gorilla'),
('COZEFFIC'),
('SSLOTSCASE'),
('LingLingo'),
('VIVO'),
('BETCKEY'),
('Surebonder'),
('BONSEN'),
('HP'),
('Westcott'),
('Ohuhu'),
('thinkor'),
('MarkDomain'),
('xydled'),
('SAKEYR'),
('Skullcandy'),
('Alpine Corporation'),
('Volcora'),
('AVERY'),
('KOSCHEAL'),
('Silver Brush Limited'),
('Super Glue'),
('Tsytyst'),
('ZEQUAN'),
('Five Star'),
('Godefa'),
('CHUNNIAO'),
('PopSockets'),
('VEWINGL'),
('MOSISO'),
('OLLY'),
('Clever Fox'),
('UPINS'),
('TOMKID'),
('Bocasal'),
('Godefa'),
('BOSMILLER'),
('Mead'),
('Canon'),
('EVETTO'),
('Wideskall'),
('HP'),
('cooloo8'),
('Post-it'),
('AISNI'),
('1 Hora'),
('Luckyear'),
('Surebonder'),
('SHOKZ'),
('NAMON'),
('deli'),
('Metamucil'),
('Reyke'),
('bloom daily planners'),
('Symcele'),
('POCHAR'),
('Boao'),
('Faber-Castell'),
('Mount-It!'),
('BesWin'),
('Anyongora'),
('Alpine Corporation'),
('Texas Instruments'),
('Durable'),
('Belkin'),
('Westcott'),
('DINOSTRIKE'),
('EooCoo'),
('Preparation H'),
('AIWOQI'),
('Targus'),
('Vitafusion'),
('AHGXG'),
('Juvale'),
('SUNEE'),
('DYMO'),
('GEM AWARDS YOUR FULL SERVICE AWARDS STORE'),
('ZAGG'),
('HOMiDEK'),
('Asvine'),
('SHANSHUI'),
('PaperPro');
COMMIT;